@startuml

/'
  図の中で目立たせたいエンティティに着色するための
  色の名前（定数）を定義します。
'/
!define MAIN_ENTITY #E2EFDA-C6E0B4
!define MAIN_ENTITY_2 #FCE4D6-F8CBAD

/' 他の色も、用途が分りやすいように名前をつけます。 '/
!define METAL #F2F2F2-D9D9D9
!define MASTER_MARK_COLOR AAFFAA
!define TRANSACTION_MARK_COLOR FFAA00
!define CHUKAN_COLOR E050CC

/'
  デフォルトのスタイルを設定します。
  この場合の指定は class です。entity ではエラーになります。
'/
skinparam class {
    BackgroundColor METAL
    BorderColor Black
    ArrowColor Black
}

package "開発対象システム" as target_system {
    /'
      マスターテーブルを M、トランザクションを T などと安直にしていますが、
      チーム内でルールを決めればなんでも良いと思います。交差テーブルは "I" とか。
      角丸四角形が描けない代替です。
      １文字なら "主" とか "従" とか日本語でも OK だったのが受ける。
     '/

    entity "会社テーブル" as company <<M,TRANSACTION_MARK_COLOR>> {
        + ID [PK]
        --
        名前
        作成日
        更新日
    }

    entity "グループテーブル" as group <<T,TRANSACTION_MARK_COLOR>> {
        + ID   [PK]
        --
        # 会社テーブル [FK]
        名前
        作成日
        更新日
    }

    entity "グループ社員テーブル" as group_users <<C,MASTER_MARK_COLOR>> MAIN_ENTITY_2 {
        + ID [PK]
        --
        # グループID[FK]
        # 社員ID[FK]
        作成日
        更新日
    }

    entity "社員" as users <<M,MASTER_MARK_COLOR>> {
        + ID [PK]
        --
        名前
        メールアドレス
        パスワード
        管理者フラグ
        作成日
        更新日
    }

    entity "明細" as skilldetail <<E,MASTER_MARK_COLOR>> MAIN_ENTITY {
        + ID [PK]
        --
        # 社員テーブル [FK]
        作成日
        更新日
        総合スコア
        平均値(グループ毎)
    }

    entity "グループサブスキルテーブル" as skill <<C,MASTER_MARK_COLOR>> MAIN_ENTITY_2 {
        + ID [PK]
        --
        # グループID[FK]
        # サブスキルID[FK]
        名前
        作成日
        更新日
    }

    entity "サブスキル" as subskill <<M,MASTER_MARK_COLOR>> {
        + ID [PK]
        --
        名前
        評価
        作成日
        更新日
    }

    /'リソース系'/
    company ||-ri-|{    group
    group   ||-ri-|{    skill
    users   ||-do-|{    skilldetail

    /'中間テーブル'/
    group_users }|-up-|| group
    group_users }|-ri-|| users


    skill }|-ri-|| subskill
}



/'note bottom of customer : コメントは\nこんなふうに書きます'/


@enduml
